# Generated by Django 4.2.3 on 2023-07-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='publisched',
            new_name='published',
        ),
    ]
